# Generated by Django 2.2.3 on 2019-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190717_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
